services:
  - type: web
    name: socket-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com
      - key: PORT
        value: 5000

  - type: web
    name: nextjs-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_SOCKET_SERVER_URL
        value: https://your-backend-url.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://your-backend-url.onrender.com
